name: Build and Push Docker Image

on:
  workflow_dispatch:
    inputs:
      build_number:
        description: "Unified Build Number"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: |
          docker build -t dieguscl/component-a:${{ github.event.inputs.build_number }} .
          docker tag dieguscl/component-a:${{ github.event.inputs.build_number }} dieguscl/component-a:latest

      - name: Push Docker Image
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push dieguscl/component-a:${{ github.event.inputs.build_number }}
          docker push dieguscl/component-a:latest

